liip_imagine:
  driver: "gd"
  loaders:
    default:
      filesystem:
        data_root: "%kernel.project_dir%/public"
  filter_sets:
    cache: ~
    my_thumb:
      quality: 75
      filters:
        thumbnail: { size: [180, 180], mode: outbound }